version: '3'
services:
  drone-db:
    image: mysql:5.7.22
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./_data/drone-db/:/var/lib/mysql/

  drone-server:
    image: drone/drone:0.8-alpine
    depends_on:
      - drone-db
    environment:
      - DRONE_HOST=${LOCALTUNNEL_PROTOCOL}${LOCALTUNNEL_SUBDOMAIN}${LOCALTUNNEL_DOMAIN}
      - DRONE_OPEN=false
      - DRONE_ADMIN=${DRONE_ADMIN}
      - DRONE_SECRET=${DRONE_SECRET}
      - DRONE_GITHUB=true
      - DRONE_GITHUB_CLIENT=${DRONE_GITHUB_CLIENT}
      - DRONE_GITHUB_SECRET=${DRONE_GITHUB_SECRET}
      - DRONE_DATABASE_DRIVER=mysql
      - DRONE_DATABASE_DATASOURCE=${MYSQL_USER}:${MYSQL_PASSWORD}@tcp(drone-db:3306)/${MYSQL_DATABASE}
    ports:
      - ${DRONE_PORT}:8000
      - 9000:9000
    restart: always

  drone-agent:
    image: drone/agent:0.8-alpine
    depends_on:
      - drone-server
    environment:
      - DRONE_SERVER=drone-server:9000
      - DRONE_SECRET=${DRONE_SECRET}
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  localtunnel:
    build: ./localtunnel/
    command: ${DRONE_PORT} --subdomain ${LOCALTUNNEL_SUBDOMAIN}
    network_mode: host
    restart: always
